name: Build Substrate Binary

on:
  # Allow it to be manually ran:
  workflow_dispatch: {}
  # Run at 2am every day
  schedule:
    - cron: "0 2 * * *"

jobs:
  tests:
    name: Build Substrate
    runs-on: ubuntu-latest
    steps:
      - name: checkout polkadot-sdk
        uses: actions/checkout@v4
        with:
          repository: paritytech/polkadot-sdk

      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler

      - name: Install WASM toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: build substrate binary
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --manifest-path substrate/bin/node/cli/Cargo.toml

      - name: upload substrate binary
        uses: actions/upload-artifact@v3
        with:
          name: nightly-substrate-binary
          path: target/release/substrate-node